# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-14 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idcs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idc',
            options={'permissions': (('view_idc', 'can view idc'),)},
        ),
    ]
