# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-04 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcs', '0002_auto_20190814_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='idc',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
