# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-04 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idcs', '0003_idc_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idc',
            name='status',
        ),
    ]
