# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idcs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idcs.Idc', verbose_name='\u6240\u5728\u673a\u623f')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'resources_cabinet',
            },
        ),
    ]
