# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-04 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_auto_20190731_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='name',
            field=models.CharField(max_length=255, verbose_name='机柜名称'),
        ),
    ]
