# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-09 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20190731_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='sn',
            field=models.CharField(db_index=True, help_text='SN', max_length=60, verbose_name='SN'),
        ),
    ]
