# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-12 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20190809_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['id'], 'permissions': (('view_server', 'can view server'),)},
        ),
    ]
