# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='mail',
            field=models.EmailField(help_text='\u8054\u7cfb\u90ae\u4ef6', max_length=32, null=True, verbose_name='\u8054\u7cfb\u90ae\u4ef6'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='remark',
            field=models.CharField(help_text='\u5907\u6ce8', max_length=300, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='tel',
            field=models.CharField(help_text='\u8054\u7cfb\u7535\u8bdd', max_length=15, null=True, verbose_name='\u8054\u7cfb\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='vendor_name',
            field=models.CharField(db_index=True, help_text='\u5382\u5546\u540d\u79f0', max_length=32, unique=True, verbose_name='\u5382\u5546\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='model_name',
            field=models.CharField(help_text='\u578b\u53f7\u540d\u79f0', max_length=20, verbose_name='\u578b\u53f7\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='vendor',
            field=models.ForeignKey(help_text='\u6240\u5c5e\u5236\u9020\u5546', on_delete=django.db.models.deletion.CASCADE, to='manufacturer.Manufacturer', verbose_name='\u6240\u5c5e\u5236\u9020\u5546'),
        ),
    ]
