# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0002_auto_20190731_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='model_name',
            field=models.CharField(help_text='\u578b\u53f7\u540d\u79f0', max_length=50, verbose_name='\u578b\u53f7\u540d\u79f0'),
        ),
    ]
